import { NewsItem } from '../types';

export const mockItems: NewsItem[] = [
  {
    id: '1',
    title: 'Pokémon TCG: Obsidian Flames Early Reveal',
    slug: 'pokemon-tcg-obsidian-flames-early-reveal',
    summary_short: 'Charizard ex takes the spotlight in the upcoming Obsidian Flames set. Pre-orders are opening sooner than expected at major retailers.',
    content_raw: 'Detailed raw content here...',
    source_url: 'https://pokemoncenter.com',
    source_name: 'Pokémon Center',
    source_type: 'scrape',
    category: 'TCG',
    sub_category: 'pokemon',
    hype_score: 10,
    engagement_count: 5000,
    image_url: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&q=80',
    is_drop_alert: true,
    is_restock: false,
    is_trending: true,
    tags: ['pokemon', 'obsidian flames', 'charizard'],
    published_at: new Date().toISOString(),
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    processing_status: 'published'
  },
  {
    id: '2',
    title: 'S.H.Figuarts Super Saiyan Goku (Legendary Super Saiyan)',
    slug: 'sh-figuarts-super-saiyan-goku',
    summary_short: 'A brand new sculpt for the legendary warrior. Pre-orders open this Friday exclusively at Premium Bandai.',
    content_raw: 'Detailed raw content here...',
    source_url: 'https://tamashiiweb.com',
    source_name: 'Tamashii Nations',
    source_type: 'twitter',
    category: 'Figures',
    sub_category: 'dragonball',
    hype_score: 9,
    engagement_count: 2400,
    image_url: 'https://images.unsplash.com/photo-1608216315259-7157ccf72671?auto=format&fit=crop&q=80',
    is_drop_alert: true,
    is_restock: false,
    is_trending: true,
    tags: ['shfiguarts', 'dragonball', 'goku'],
    published_at: new Date(Date.now() - 3600000).toISOString(),
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    processing_status: 'published'
  },
  {
    id: '3',
    title: 'Rolex Submariner Restock Alert - Select ADs',
    slug: 'rolex-submariner-restock',
    summary_short: 'Reports indicate a rare mid-month shipment of steel Submariners arriving at Authorized Dealers globally.',
    content_raw: 'Detailed raw content here...',
    source_url: 'https://reddit.com/r/watches',
    source_name: 'r/Watches',
    source_type: 'reddit',
    category: 'Watches',
    sub_category: 'rolex',
    hype_score: 8,
    engagement_count: 1200,
    is_drop_alert: false,
    is_restock: true,
    is_trending: true,
    tags: ['rolex', 'submariner', 'restock'],
    published_at: new Date(Date.now() - 7200000).toISOString(),
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    processing_status: 'published'
  },
  {
    id: '4',
    title: 'One Piece Card Game: OP-07 500 Years in the Future',
    slug: 'one-piece-card-game-op07',
    summary_short: 'The new OP-07 set introduces powerful new leaders. Booster boxes are currently seeing high demand.',
    content_raw: 'Detailed raw content here...',
    source_url: 'https://en.onepiece-cardgame.com',
    source_name: 'OPCG Official',
    source_type: 'scrape',
    category: 'TCG',
    sub_category: 'onepiece',
    hype_score: 7,
    engagement_count: 800,
    image_url: 'https://images.unsplash.com/photo-1541562232579-512a21360020?auto=format&fit=crop&q=80',
    is_drop_alert: false,
    is_restock: false,
    is_trending: false,
    tags: ['one piece', 'tcg', 'op-07'],
    published_at: new Date(Date.now() - 14400000).toISOString(),
    scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    processing_status: 'published'
  }
];
